
Set c = CreateObject( "ActiveXperts.NMConstants" )

WScript.Echo "CHECKTYPE_UNDEFINED: " & c.CHECKTYPE_UNDEFINED
WScript.Echo "CHECKTYPE_FOLDER: " & c.CHECKTYPE_FOLDER

WScript.Echo "CHECKTYPE_ADOSQL: " & c.CHECKTYPE_ADOSQL
WScript.Echo "CHECKTYPE_CPU: " & c.CHECKTYPE_CPU
WScript.Echo "CHECKTYPE_DIRSIZE: " & c.CHECKTYPE_DIRSIZE
WScript.Echo "CHECKTYPE_DISKS: " & c.CHECKTYPE_DISKS
WScript.Echo "CHECKTYPE_DISKSPACE: " & c.CHECKTYPE_DISKSPACE
WScript.Echo "CHECKTYPE_DNS: " & c.CHECKTYPE_DNS
WScript.Echo "CHECKTYPE_EVENTLOG: " & c.CHECKTYPE_EVENTLOG
WScript.Echo "CHECKTYPE_FILE: " & c.CHECKTYPE_FILE
WScript.Echo "CHECKTYPE_FLOPPY: " & c.CHECKTYPE_FLOPPY
WScript.Echo "CHECKTYPE_FTP: " & c.CHECKTYPE_FTP
WScript.Echo "CHECKTYPE_HTTP: " & c.CHECKTYPE_HTTP
WScript.Echo "CHECKTYPE_HUMIDITY: " & c.CHECKTYPE_HUMIDITY
WScript.Echo "CHECKTYPE_ICMP: " & c.CHECKTYPE_ICMP
WScript.Echo "CHECKTYPE_IMAP: " & c.CHECKTYPE_IMAP
WScript.Echo "CHECKTYPE_MEMORY: " & c.CHECKTYPE_MEMORY
WScript.Echo "CHECKTYPE_MSTSE: " & c.CHECKTYPE_MSTSE
WScript.Echo "CHECKTYPE_NNTP: " & c.CHECKTYPE_NNTP
WScript.Echo "CHECKTYPE_NTP: " & c.CHECKTYPE_NTP
WScript.Echo "CHECKTYPE_ODBC: " & c.CHECKTYPE_ODBC
WScript.Echo "CHECKTYPE_ORACLE: " & c.CHECKTYPE_ORACLE
WScript.Echo "CHECKTYPE_POP3: " & c.CHECKTYPE_POP3
WScript.Echo "CHECKTYPE_PRINTER: " & c.CHECKTYPE_PRINTER
WScript.Echo "CHECKTYPE_PROCESS: " & c.CHECKTYPE_PROCESS
WScript.Echo "CHECKTYPE_RSH: " & c.CHECKTYPE_RSH
WScript.Echo "CHECKTYPE_SERVICE: " & c.CHECKTYPE_SERVICE
WScript.Echo "CHECKTYPE_SMTP: " & c.CHECKTYPE_SMTP
WScript.Echo "CHECKTYPE_SNMP: " & c.CHECKTYPE_SNMP
WScript.Echo "CHECKTYPE_TEMPERATURE: " & c.CHECKTYPE_TEMPERATURE
WScript.Echo "CHECKTYPE_TCPIP: " & c.CHECKTYPE_TCPIP
WScript.Echo "CHECKTYPE_VBSCRIPT: " & c.CHECKTYPE_VBSCRIPT
WScript.Echo "CHECKTYPE_WETNESS: " & c.CHECKTYPE_WETNESS


